import Link from "next/link";import {ArrowUpRight,Gamepad2,Layers3,MonitorPlay,Trophy} from "lucide-react";import Hero from "@/components/Hero";import GameGrid from "@/components/GameGrid";import SectionHeading from "@/components/SectionHeading";import {rawgFetch} from "@/lib/rawg";
export const revalidate=1800;
async function getHomeData(){const [trending,topRated,genres]=await Promise.all([rawgFetch("/games",{ordering:"-added",page_size:7}),rawgFetch("/games",{ordering:"-rating",page_size:8}),rawgFetch("/genres",{page_size:12})]);return {trending:trending.results||[],topRated:topRated.results||[],genres:genres.results||[],count:trending.count||0}}
export default async function HomePage(){const {trending,topRated,genres,count}=await getHomeData();return <>
 <Hero games={trending} catalogCount={count}/>
 <section className="trust-strip"><div className="content-shell trust-grid"><div><span className="trust-icon"><Gamepad2 size={18}/></span><strong>Real catalog data</strong><p>Game metadata comes from RAWG.</p></div><div><span className="trust-icon"><MonitorPlay size={18}/></span><strong>Platforms & releases</strong><p>See where and when games launched.</p></div><div><span className="trust-icon"><Layers3 size={18}/></span><strong>Visual discovery</strong><p>Browse covers and screenshots.</p></div><div><span className="trust-icon"><Trophy size={18}/></span><strong>Ratings</strong><p>Surface real community scores.</p></div></div></section>
 <section className="content-shell section-space"><SectionHeading eyebrow="01 / Trending" title="Games everyone is watching" subtitle="Freshly active titles from the live RAWG catalog." action={<Link href="/games" className="section-action">View library <ArrowUpRight size={16}/></Link>}/><GameGrid games={trending}/></section>
 <section className="genre-section"><div className="content-shell section-space"><SectionHeading eyebrow="02 / Browse by mood" title="Choose your kind of world" subtitle="Jump straight into a genre and discover what fits."/><div className="genre-grid">{genres.slice(0,8).map((g,i)=><Link key={g.id} href={`/games?genres=${g.slug}`} className="genre-tile"><span>{String(i+1).padStart(2,"0")}</span><strong>{g.name}</strong><ArrowUpRight size={18}/></Link>)}</div></div></section>
 <section className="content-shell section-space"><div className="feature-panel"><div><p className="section-eyebrow">03 / Made for discovery</p><h2>Less noise.<br/><em>More worlds.</em></h2><p>Search a title, scan the facts, open the profile and see its real screenshots. Every visible game detail is sourced from the API rather than invented filler.</p><Link href="/games" className="primary-button">Start exploring <ArrowUpRight size={16}/></Link></div><div className="feature-orbit"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-core"><Gamepad2 size={42}/><span>LIVE</span></div></div></div></section>
 <section className="top-rated-section"><div className="content-shell section-space"><SectionHeading eyebrow="04 / Rated" title="Standout games" subtitle="Titles ordered by community rating from RAWG." action={<Link href="/games?ordering=-rating" className="section-action">View ratings <ArrowUpRight size={16}/></Link>}/><GameGrid games={topRated}/></div></section>
 </>}
